import os
import logging
from datetime import datetime
from xhtml2pdf import pisa

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    filename='server_logs.txt'
)
logger = logging.getLogger('pdf_generator')


def generate_html(user_data):
    """Creates basic HTML content from user data"""
    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                padding: 40px;
            }}
            h1 {{
                color: #ff9562;
            }}
            h2 {{
                color: #ff7f42;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            th, td {{
                border: 1px solid #ccc;
                padding: 10px;
                text-align: left;
            }}
            th {{
                background-color: #ff9562;
                color: white;
            }}
            .footer {{
                margin-top: 40px;
                font-size: 10px;
                color: gray;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        <h1>MonuMe Tracker - Performance Summary</h1>
        <p><strong>User:</strong> {user_data.get('user_name', 'User')}</p>
        <p><strong>Date:</strong> {user_data.get('date', datetime.now().strftime('%Y-%m-%d'))}</p>
        <h2>Performance Metrics</h2>
        <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Opal Demos</td><td>{user_data.get('opal_demos', 0)}</td></tr>
            <tr><td>Opal Sales</td><td>{user_data.get('opal_sales', 0)}</td></tr>
            <tr><td>Scan Demos</td><td>{user_data.get('scan_demos', 0)}</td></tr>
            <tr><td>Scan Sold</td><td>{user_data.get('scan_sold', 0)}</td></tr>
            <tr><td>Net Sales</td><td>${user_data.get('net_sales', 0)}</td></tr>
            <tr><td>Hours Worked</td><td>{user_data.get('hours_worked', 0)}</td></tr>
            <tr><td>Success Rate</td><td>{user_data.get('success_rate', 0)}%</td></tr>
            <tr><td>Sales per Hour</td><td>${user_data.get('sales_per_hour', 0)}</td></tr>
        </table>
        <div class="footer">
            This is an automated report generated by MonuMe Tracker.
        </div>
    </body>
    </html>
    """
    return html


def generate_performance_pdf(user_data):
    """Generate PDF from HTML string using xhtml2pdf"""
    try:
        os.makedirs('temp', exist_ok=True)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"temp/performance_summary_{user_data.get('user_id', 'user')}_{timestamp}.pdf"

        html = generate_html(user_data)

        with open(filename, "w+b") as f:
            pisa_status = pisa.CreatePDF(html, dest=f)

        if pisa_status.err:
            logger.error("PDF generation failed")
            return None
        return filename
    except Exception as e:
        logger.error(f"Error generating PDF: {str(e)}")
        return None


def generate_test_pdf():
    """Generate a test PDF for email testing"""
    try:
        test_data = {
            'user_id': 'test',
            'user_name': 'Test User',
            'date': datetime.now().strftime('%Y-%m-%d'),
            'opal_demos': 5,
            'opal_sales': 2,
            'scan_demos': 8,
            'scan_sold': 3,
            'net_sales': 750,
            'hours_worked': 8,
            'success_rate': 62.5,
            'sales_per_hour': 93.75
        }
        return generate_performance_pdf(test_data)
    except Exception as e:
        logger.error(f"Error generating test PDF: {str(e)}")
        return None

